#!/usr/bin/env python3
import argparse
import json
from pathlib import Path
import shutil
import sys
try:
    import tomllib as _tomllib
except ModuleNotFoundError:
    _tomllib = None


HOME = Path.home()
FLOW_HOME = HOME / ".flow"
FRAMEWORK_DIR = FLOW_HOME / "framework"
TEMPLATES_DIR = FRAMEWORK_DIR / "templates" / "framework"
USER_BIN_DIR = HOME / ".local" / "bin"
FLOW_CONFIG = FLOW_HOME / "config.toml"
GENERATED_MARKER = "Generated by flow."


def repo_root() -> Path:
    cwd = Path.cwd().resolve()
    for path in [cwd, *cwd.parents]:
        if (path / ".flow").exists() or (path / ".git").exists():
            return path
    return cwd


def ensure_dir(path: Path) -> None:
    path.mkdir(parents=True, exist_ok=True)


def ensure_file(path: Path, content: str) -> None:
    if path.exists():
        return
    ensure_dir(path.parent)
    path.write_text(content)


def copy_if_missing(src: Path, dest: Path) -> None:
    if dest.exists():
        return
    if src.is_dir():
        shutil.copytree(src, dest)
    else:
        ensure_dir(dest.parent)
        shutil.copy2(src, dest)


def parse_toml_value(raw: str):
    raw = raw.strip()
    if raw.startswith('"') and raw.endswith('"'):
        return raw[1:-1]
    if raw in {"true", "false"}:
        return raw == "true"
    if raw.isdigit():
        return int(raw)
    raise ValueError(f"unsupported TOML value: {raw}")


def assign_nested(container: dict, dotted_key: str, value) -> None:
    parts = dotted_key.split(".")
    current = container
    for part in parts[:-1]:
        current = current.setdefault(part, {})
    current[parts[-1]] = value


def parse_simple_toml(text: str) -> dict:
    root: dict = {}
    current = root
    for raw_line in text.splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith("[[") and line.endswith("]]"):
            path = line[2:-2].strip().split(".")
            current = root
            for part in path[:-1]:
                current = current.setdefault(part, {})
            current = current.setdefault(path[-1], [])
            current.append({})
            current = current[-1]
            continue
        if line.startswith("[") and line.endswith("]"):
            path = line[1:-1].strip().split(".")
            current = root
            for part in path:
                current = current.setdefault(part, {})
            continue
        key, value = line.split("=", 1)
        assign_nested(current, key.strip(), parse_toml_value(value))
    return root


def read_toml(path: Path) -> dict:
    text = path.read_text()
    if _tomllib is not None:
        return _tomllib.loads(text)
    return parse_simple_toml(text)


def rel_posix(path: Path, root: Path) -> str:
    return path.relative_to(root).as_posix()


def render_skill(name: str, description: str, source_path: str, body: str) -> str:
    lines = [
        "---",
        f"name: {name}",
        f"description: {description}",
        "---",
        "",
        f"<!-- {GENERATED_MARKER} Edit `.flow/{source_path}` and run `flow sync claude`. -->",
        "",
        body.rstrip(),
        "",
        "## Invocation Arguments",
        "",
        "If arguments were provided after the skill name, treat them as the specific focus for this run:",
        "",
        "`$ARGUMENTS`",
        "",
    ]
    return "\n".join(lines)


def insert_generated_marker(source_path: str, body: str) -> str:
    marker = f"<!-- {GENERATED_MARKER} Edit `.flow/{source_path}` and run `flow sync claude`. -->"
    if body.startswith("---\n"):
        closing = body.find("\n---\n", 4)
        if closing != -1:
            insert_at = closing + 5
            return body[:insert_at] + "\n" + marker + "\n" + body[insert_at:].lstrip("\n")
    return marker + "\n\n" + body


def build_managed_manifest(entries: list[dict]) -> str:
    lines = [
        "[managed]",
        'generator = "flow"',
        "version = 1",
        'target = "claude"',
        "",
    ]
    for entry in entries:
        lines.extend(
            [
                "[[files]]",
                f'path = "{entry["path"]}"',
                f'kind = "{entry["kind"]}"',
                f'source = "{entry["source"]}"',
                "",
            ]
        )
    return "\n".join(lines)


def read_managed_paths(path: Path) -> set[Path]:
    if not path.exists():
        return set()
    data = read_toml(path)
    files = data.get("files", [])
    return {repo_root() / entry["path"] for entry in files if "path" in entry}


def remove_empty_parents(path: Path, stop_at: Path) -> None:
    current = path.parent
    while current != stop_at and current.exists():
        try:
            current.rmdir()
        except OSError:
            return
        current = current.parent


def load_flow_manifest(flow_dir: Path) -> tuple[Path, dict]:
    manifest_path = flow_dir / "flow.toml"
    if not manifest_path.exists():
        raise FileNotFoundError(f"missing manifest: {manifest_path}")
    return manifest_path, read_toml(manifest_path)


def desired_claude_outputs(root: Path, flow_dir: Path, manifest: dict) -> tuple[dict[Path, str], list[dict]]:
    claude = manifest["claude"]
    outputs: dict[Path, str] = {}
    managed_entries: list[dict] = []

    for command in claude.get("commands", []):
        source_rel = command["source"]
        source_path = flow_dir / source_rel
        target = root / claude["skill_dir"] / command["name"] / "SKILL.md"
        content = render_skill(
            command["name"],
            command["description"],
            source_rel,
            source_path.read_text(),
        )
        outputs[target] = content
        managed_entries.append(
            {
                "path": rel_posix(target, root),
                "kind": "skill",
                "source": f'.flow/{source_rel}',
            }
        )

    for agent in claude.get("agents", []):
        source_rel = agent["source"]
        source_path = flow_dir / source_rel
        target = root / claude["agent_dir"] / f'{agent["name"]}.md'
        content = insert_generated_marker(source_rel, source_path.read_text())
        outputs[target] = content
        managed_entries.append(
            {
                "path": rel_posix(target, root),
                "kind": "agent",
                "source": f'.flow/{source_rel}',
            }
        )

    managed_manifest_path = root / claude["managed_manifest"]
    outputs[managed_manifest_path] = build_managed_manifest(managed_entries)
    managed_entries.append(
        {
            "path": rel_posix(managed_manifest_path, root),
            "kind": "managed-manifest",
            "source": ".flow/flow.toml",
        }
    )
    outputs[managed_manifest_path] = build_managed_manifest(managed_entries)
    return outputs, managed_entries


def sync_outputs(root: Path, desired: dict[Path, str], previous_managed: set[Path], check: bool) -> int:
    desired_paths = set(desired)
    conflicts: list[Path] = []
    changed: list[Path] = []
    removed: list[Path] = []

    for target, content in desired.items():
        if target.exists():
            current = target.read_text()
            if current == content:
                continue
            if target not in previous_managed and GENERATED_MARKER not in current:
                conflicts.append(target)
                continue
        changed.append(target)

    stale = [path for path in previous_managed if path not in desired_paths and path.exists()]

    if conflicts:
        print("sync claude found unmanaged conflicts:")
        for path in conflicts:
            print(f"- {path}")
        print("resolve them manually or move the source of truth into `.flow/` first")
        return 1

    if check:
        if not changed and not stale:
            print("claude sync check: up to date")
            return 0
        print("claude sync check: drift detected")
        for path in changed:
            print(f"- update: {path}")
        for path in stale:
            print(f"- remove: {path}")
        return 1

    for path in stale:
        path.unlink()
        remove_empty_parents(path, root)
        removed.append(path)

    for target, content in desired.items():
        ensure_dir(target.parent)
        if not target.exists() or target.read_text() != content:
            target.write_text(content)

    print("claude sync wrote managed files:")
    for path in changed:
        print(f"- {path}")
    for path in removed:
        print(f"- removed: {path}")
    if not changed and not removed:
        print("- no changes needed")
    return 0


def setup_machine() -> int:
    ensure_dir(FLOW_HOME)
    ensure_dir(USER_BIN_DIR)
    ensure_dir(FLOW_HOME / "hooks")
    ensure_dir(FLOW_HOME / "templates")
    ensure_dir(FLOW_HOME / "user")
    ensure_dir(FLOW_HOME / "logs")
    ensure_file(
        FLOW_CONFIG,
        "[flow]\nframework_home = \"~/.flow/framework\"\nlauncher = \"~/.local/bin/flow\"\n",
    )
    print(f"flow home ready: {FLOW_HOME}")
    print(f"config:     {FLOW_CONFIG}")
    print("next: run `flow setup project` inside a repository")
    return 0


def setup_project() -> int:
    root = repo_root()
    target = root / ".flow"
    ensure_dir(target)

    for item in TEMPLATES_DIR.iterdir():
        copy_if_missing(item, target / item.name)

    print(f"project scaffold ready: {target}")
    print("next: fill in .flow/PROJECT.md and run `flow sync claude` later")
    return 0


def doctor() -> int:
    root = repo_root()
    flow_dir = root / ".flow"
    manifest_ok = (flow_dir / "flow.toml").exists()
    managed_ok = (root / ".claude" / "flow.managed.toml").exists()
    skills_dir = root / ".claude" / "skills"
    agents_dir = root / ".claude" / "agents"

    print(f"python:      {sys.executable}")
    print(f"flow home:   {FLOW_HOME}")
    print(f"framework:   {FRAMEWORK_DIR}")
    print(f"repo:        {root}")
    print(f"config:      {'ok' if FLOW_CONFIG.exists() else 'missing'}")
    print(f"launcher:    {'ok' if (USER_BIN_DIR / 'flow').exists() else 'missing'}")
    print(f"templates:   {'ok' if TEMPLATES_DIR.exists() else 'missing'}")
    print(f"repo .flow:  {'ok' if flow_dir.exists() else 'missing'}")
    print(f"manifest:    {'ok' if manifest_ok else 'missing'}")
    print(f"claude sync: {'ok' if managed_ok else 'missing'}")
    print(f"skills dir:  {'ok' if skills_dir.exists() else 'missing'}")
    print(f"agents dir:  {'ok' if agents_dir.exists() else 'missing'}")
    return 0


def bootstrap() -> int:
    root = repo_root()
    flow_dir = root / ".flow"
    if not flow_dir.exists():
        print("repo is missing .flow; run `flow setup project` first")
        return 1

    required = [
        flow_dir / "flow.toml",
        flow_dir / "FRAMEWORK.md",
        flow_dir / "PROJECT.md",
        flow_dir / "commands",
        flow_dir / "agents",
        flow_dir / "standards",
        flow_dir / "project",
        flow_dir / "memory",
        flow_dir / "templates",
    ]
    missing = [str(p) for p in required if not p.exists()]
    if missing:
        print("bootstrap found missing framework paths:")
        for path in missing:
            print(f"- {path}")
        return 1

    print(f"bootstrap ok: {flow_dir}")
    print("next: run `flow doctor` or `flow sync claude`")
    return 0


def sync_claude(check: bool = False) -> int:
    root = repo_root()
    flow_dir = root / ".flow"
    if not flow_dir.exists():
        print("repo is missing .flow; run `flow setup project` first")
        return 1

    try:
        manifest_path, manifest = load_flow_manifest(flow_dir)
    except FileNotFoundError as err:
        print(str(err))
        return 1

    previous_managed = read_managed_paths(root / manifest["claude"]["managed_manifest"])
    desired, _managed_entries = desired_claude_outputs(root, flow_dir, manifest)
    result = sync_outputs(root, desired, previous_managed, check=check)
    if result == 0:
        mode = "check" if check else "sync"
        print(f"claude {mode} complete from {manifest_path}")
    return result


def main() -> int:
    parser = argparse.ArgumentParser(prog="flow")
    sub = parser.add_subparsers(dest="command", required=True)

    setup = sub.add_parser("setup")
    setup_sub = setup.add_subparsers(dest="setup_target", required=True)
    setup_sub.add_parser("machine")
    setup_sub.add_parser("project")

    sub.add_parser("doctor")
    sub.add_parser("bootstrap")
    sync = sub.add_parser("sync")
    sync.add_argument("target", choices=["claude"])
    sync.add_argument("--check", action="store_true")

    args = parser.parse_args()

    if args.command == "setup" and args.setup_target == "machine":
        return setup_machine()
    if args.command == "setup" and args.setup_target == "project":
        return setup_project()
    if args.command == "doctor":
        return doctor()
    if args.command == "bootstrap":
        return bootstrap()
    if args.command == "sync" and args.target == "claude":
        return sync_claude(check=args.check)
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
