#!/usr/bin/env python3
import argparse
import json
from pathlib import Path
import shutil
import sys
try:
    import tomllib as _tomllib
except ModuleNotFoundError:
    _tomllib = None


HOME = Path.home()
FLOW_HOME = HOME / ".flow"
FRAMEWORK_DIR = FLOW_HOME / "framework"
TEMPLATES_DIR = FRAMEWORK_DIR / "templates" / "framework"
USER_BIN_DIR = HOME / ".local" / "bin"
FLOW_CONFIG = FLOW_HOME / "config.toml"
GENERATED_MARKER = "Generated by flow."


def repo_root() -> Path:
    cwd = Path.cwd().resolve()
    for path in [cwd, *cwd.parents]:
        if (path / ".flow").exists() or (path / ".git").exists():
            return path
    return cwd


def ensure_dir(path: Path) -> None:
    path.mkdir(parents=True, exist_ok=True)


def ensure_file(path: Path, content: str) -> None:
    if path.exists():
        return
    ensure_dir(path.parent)
    path.write_text(content)


def copy_if_missing(src: Path, dest: Path) -> None:
    if dest.exists():
        return
    if src.is_dir():
        shutil.copytree(src, dest)
    else:
        ensure_dir(dest.parent)
        shutil.copy2(src, dest)


def sync_missing_tree(src: Path, dest: Path) -> tuple[int, int]:
    added = 0
    skipped = 0
    if src.is_dir():
        ensure_dir(dest)
        for child in src.iterdir():
            child_added, child_skipped = sync_missing_tree(child, dest / child.name)
            added += child_added
            skipped += child_skipped
        return added, skipped
    if dest.exists():
        return 0, 1
    ensure_dir(dest.parent)
    shutil.copy2(src, dest)
    return 1, 0


def parse_toml_value(raw: str):
    raw = raw.strip()
    if raw.startswith('"') and raw.endswith('"'):
        return raw[1:-1]
    if raw in {"true", "false"}:
        return raw == "true"
    if raw.isdigit():
        return int(raw)
    raise ValueError(f"unsupported TOML value: {raw}")


def assign_nested(container: dict, dotted_key: str, value) -> None:
    parts = dotted_key.split(".")
    current = container
    for part in parts[:-1]:
        current = current.setdefault(part, {})
    current[parts[-1]] = value


def parse_simple_toml(text: str) -> dict:
    root: dict = {}
    current = root
    for raw_line in text.splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith("[[") and line.endswith("]]"):
            path = line[2:-2].strip().split(".")
            current = root
            for part in path[:-1]:
                current = current.setdefault(part, {})
            current = current.setdefault(path[-1], [])
            current.append({})
            current = current[-1]
            continue
        if line.startswith("[") and line.endswith("]"):
            path = line[1:-1].strip().split(".")
            current = root
            for part in path:
                current = current.setdefault(part, {})
            continue
        key, value = line.split("=", 1)
        assign_nested(current, key.strip(), parse_toml_value(value))
    return root


def read_toml(path: Path) -> dict:
    text = path.read_text()
    if _tomllib is not None:
        return _tomllib.loads(text)
    return parse_simple_toml(text)


def rel_posix(path: Path, root: Path) -> str:
    return path.relative_to(root).as_posix()


def render_skill(name: str, description: str, source_path: str, body: str) -> str:
    lines = [
        "---",
        f"name: {name}",
        f"description: {description}",
        "---",
        "",
        f"<!-- {GENERATED_MARKER} Edit `.flow/{source_path}` and run `flow sync claude`. -->",
        "",
        body.rstrip(),
        "",
        "## Invocation Arguments",
        "",
        "If arguments were provided after the skill name, treat them as the specific focus for this run:",
        "",
        "`$ARGUMENTS`",
        "",
    ]
    return "\n".join(lines)


def render_codex_skill(source_path: str, body: str) -> str:
    lines = [
        f"<!-- {GENERATED_MARKER} Edit `.flow/{source_path}` and rerun `flow sync codex`. -->",
        "",
        body.rstrip(),
        "",
        "## Invocation Arguments",
        "",
        "If arguments were provided after the skill name, treat them as the specific focus for this run:",
        "",
        "`$ARGUMENTS`",
        "",
    ]
    return "\n".join(lines)


def build_skill_frontmatter(name: str, command: dict, skill_defaults: dict) -> list[str]:
    frontmatter = {
        "name": name,
        "description": command["description"],
    }

    merged = dict(skill_defaults)
    merged.update(command)

    field_map = [
        ("when_to_use", "when-to-use"),
        ("argument_hint", "argument-hint"),
        ("disable_model_invocation", "disable-model-invocation"),
        ("user_invocable", "user-invocable"),
        ("allowed_tools", "allowed-tools"),
        ("model", "model"),
        ("effort", "effort"),
        ("context", "context"),
        ("agent", "agent"),
    ]
    for source_key, target_key in field_map:
        if source_key in merged:
            frontmatter[target_key] = merged[source_key]

    lines = ["---"]
    for key, value in frontmatter.items():
        if isinstance(value, bool):
            rendered = "true" if value else "false"
        else:
            rendered = str(value)
        lines.append(f"{key}: {rendered}")
    lines.append("---")
    return lines


def render_skill_from_command(command: dict, skill_defaults: dict) -> str:
    source_path = command["source"]
    body = command["_body"]
    lines = build_skill_frontmatter(command["name"], command, skill_defaults)
    lines.extend(
        [
            "",
            f"<!-- {GENERATED_MARKER} Edit `.flow/{source_path}` and run `flow sync claude`. -->",
            "",
            body.rstrip(),
            "",
            "## Invocation Arguments",
            "",
            "If arguments were provided after the skill name, treat them as the specific focus for this run:",
            "",
            "`$ARGUMENTS`",
            "",
        ]
    )
    return "\n".join(lines)


def insert_generated_marker(source_path: str, body: str) -> str:
    marker = f"<!-- {GENERATED_MARKER} Edit `.flow/{source_path}` and run `flow sync claude`. -->"
    if body.startswith("---\n"):
        closing = body.find("\n---\n", 4)
        if closing != -1:
            insert_at = closing + 5
            return body[:insert_at] + "\n" + marker + "\n" + body[insert_at:].lstrip("\n")
    return marker + "\n\n" + body


def build_managed_manifest(target_name: str, entries: list[dict]) -> str:
    lines = [
        "[managed]",
        'generator = "flow"',
        "version = 2",
        f'target = "{target_name}"',
        'source_manifest = ".flow/flow.toml"',
        'preserve_unmanaged = true',
        "",
    ]
    for entry in entries:
        lines.extend(
            [
                "[[files]]",
                f'path = "{entry["path"]}"',
                f'kind = "{entry["kind"]}"',
                f'source = "{entry["source"]}"',
                f'sync_mode = "{entry["sync_mode"]}"',
                "",
            ]
        )
    return "\n".join(lines)


def read_managed_paths(root: Path, path: Path) -> set[Path]:
    if not path.exists():
        return set()
    data = read_toml(path)
    files = data.get("files", [])
    return {root / entry["path"] for entry in files if "path" in entry}


def remove_empty_parents(path: Path, stop_at: Path) -> None:
    current = path.parent
    while current != stop_at and current.exists():
        try:
            current.rmdir()
        except OSError:
            return
        current = current.parent


def load_flow_manifest(flow_dir: Path) -> tuple[Path, dict]:
    manifest_path = flow_dir / "flow.toml"
    if not manifest_path.exists():
        raise FileNotFoundError(f"missing manifest: {manifest_path}")
    return manifest_path, read_toml(manifest_path)


def read_json(path: Path) -> dict:
    if not path.exists():
        return {}
    return json.loads(path.read_text())


def remove_managed_flow_hooks(settings: dict) -> dict:
    hooks = settings.get("hooks")
    if not isinstance(hooks, dict):
        return settings

    cleaned_events: dict[str, list] = {}
    for event, groups in hooks.items():
        if not isinstance(groups, list):
            continue
        cleaned_groups = []
        for group in groups:
            handlers = group.get("hooks", [])
            kept_handlers = []
            for handler in handlers:
                command = handler.get("command", "")
                if handler.get("type") == "command" and "/.claude/hooks/flow-" in command:
                    continue
                kept_handlers.append(handler)
            if kept_handlers:
                updated = dict(group)
                updated["hooks"] = kept_handlers
                cleaned_groups.append(updated)
        if cleaned_groups:
            cleaned_events[event] = cleaned_groups

    if cleaned_events:
        settings["hooks"] = cleaned_events
    else:
        settings.pop("hooks", None)
    return settings


def build_claude_settings(root: Path, runtime: dict) -> str:
    settings_path = root / runtime["settings_file"]
    settings = remove_managed_flow_hooks(read_json(settings_path))
    hooks = settings.setdefault("hooks", {})

    for hook in runtime.get("hooks", []):
        event = hook["event"]
        groups = hooks.setdefault(event, [])
        groups.append(
            {
                "matcher": hook["matcher"],
                "hooks": [
                    {
                        "type": hook["type"],
                        "command": f'"$CLAUDE_PROJECT_DIR"/.claude/hooks/{hook["script"]}',
                    }
                ],
            }
        )

    return json.dumps(settings, indent=2, sort_keys=True) + "\n"


def desired_claude_outputs(
    root: Path, flow_dir: Path, manifest: dict, manifest_rel: str
) -> tuple[dict[Path, str], list[dict], set[Path]]:
    runtime = manifest["claude"]
    skill_defaults = runtime.get("skill_defaults", {})
    agent_defaults = runtime.get("agent_defaults", {})
    outputs: dict[Path, str] = {}
    managed_entries: list[dict] = []
    mergeable_paths: set[Path] = set()

    for command in runtime.get("commands", []):
        source_rel = command["source"]
        source_path = flow_dir / source_rel
        target = root / runtime["skill_dir"] / command["name"] / "SKILL.md"
        command_with_body = dict(command)
        command_with_body["_body"] = source_path.read_text()
        content = render_skill_from_command(command_with_body, skill_defaults)
        outputs[target] = content
        managed_entries.append(
            {
                "path": rel_posix(target, root),
                "kind": "skill",
                "source": f'.flow/{source_rel}',
                "sync_mode": "replace",
            }
        )

    for agent in runtime.get("agents", []):
        source_rel = agent["source"]
        source_path = flow_dir / source_rel
        target = root / runtime["agent_dir"] / f'{agent["name"]}.md'
        generation_mode = agent.get("generation_mode", agent_defaults.get("generation_mode", "verbatim"))
        if generation_mode != "verbatim":
            raise ValueError(f"unsupported agent generation mode: {generation_mode}")
        content = insert_generated_marker(source_rel, source_path.read_text())
        outputs[target] = content
        managed_entries.append(
            {
                "path": rel_posix(target, root),
                "kind": "agent",
                "source": f'.flow/{source_rel}',
                "sync_mode": "replace",
            }
        )

    for hook in runtime.get("hooks", []):
        source = FRAMEWORK_DIR / "hooks" / hook["script"]
        target = root / runtime["hook_dir"] / hook["script"]
        content = source.read_text()
        outputs[target] = content
        managed_entries.append(
            {
                "path": rel_posix(target, root),
                "kind": "hook-script",
                "source": f'flow/hooks/{hook["script"]}',
                "sync_mode": "replace",
            }
        )

    settings_path = root / runtime["settings_file"]
    outputs[settings_path] = build_claude_settings(root, runtime)
    mergeable_paths.add(settings_path)
    managed_entries.append(
        {
            "path": rel_posix(settings_path, root),
            "kind": "settings",
            "source": manifest_rel,
            "sync_mode": "merge",
        }
    )

    managed_manifest_path = root / runtime["managed_manifest"]
    outputs[managed_manifest_path] = build_managed_manifest("claude", managed_entries)
    managed_entries.append(
        {
            "path": rel_posix(managed_manifest_path, root),
            "kind": "managed-manifest",
            "source": manifest_rel,
            "sync_mode": "replace",
        }
    )
    outputs[managed_manifest_path] = build_managed_manifest("claude", managed_entries)
    return outputs, managed_entries, mergeable_paths


def desired_codex_outputs(
    root: Path, flow_dir: Path, manifest: dict, manifest_rel: str
) -> tuple[dict[Path, str], list[dict], set[Path]]:
    runtime = manifest["codex"]
    outputs: dict[Path, str] = {}
    managed_entries: list[dict] = []
    mergeable_paths: set[Path] = set()

    for command in runtime.get("commands", []):
        source_rel = command["source"]
        source_path = flow_dir / source_rel
        target = root / runtime["skill_dir"] / command["name"] / "SKILL.md"
        outputs[target] = render_codex_skill(source_rel, source_path.read_text())
        managed_entries.append(
            {
                "path": rel_posix(target, root),
                "kind": "skill",
                "source": f'.flow/{source_rel}',
                "sync_mode": "replace",
            }
        )

    managed_manifest_path = root / runtime["managed_manifest"]
    outputs[managed_manifest_path] = build_managed_manifest("codex", managed_entries)
    managed_entries.append(
        {
            "path": rel_posix(managed_manifest_path, root),
            "kind": "managed-manifest",
            "source": manifest_rel,
            "sync_mode": "replace",
        }
    )
    outputs[managed_manifest_path] = build_managed_manifest("codex", managed_entries)
    return outputs, managed_entries, mergeable_paths


def analyze_sync(
    desired: dict[Path, str], previous_managed: set[Path], mergeable_paths: set[Path]
) -> tuple[list[Path], list[Path], list[Path]]:
    desired_paths = set(desired)
    conflicts: list[Path] = []
    changed: list[Path] = []

    for target, content in desired.items():
        if target.exists():
            current = target.read_text()
            if current == content:
                continue
            if (
                target not in previous_managed
                and target not in mergeable_paths
                and GENERATED_MARKER not in current
            ):
                conflicts.append(target)
                continue
        changed.append(target)

    stale = [path for path in previous_managed if path not in desired_paths and path.exists()]
    return conflicts, changed, stale


def runtime_status(
    root: Path, flow_dir: Path, manifest_path: Path, manifest: dict, target: str
) -> tuple[str, bool]:
    runtime = manifest.get(target)
    if not isinstance(runtime, dict):
        return "n/a", False

    managed_path = root / runtime["managed_manifest"]
    managed_ok = managed_path.exists()
    try:
        previous_managed = read_managed_paths(root, managed_path)
        desired, _managed_entries, mergeable_paths = desired_outputs_for_target(
            target, root, flow_dir, manifest, rel_posix(manifest_path, root)
        )
        conflicts, changed, stale = analyze_sync(desired, previous_managed, mergeable_paths)
        if conflicts:
            return "conflict", managed_ok
        if changed or stale:
            return "stale", managed_ok
        return "clean", managed_ok
    except Exception:
        return "error", managed_ok


def sync_outputs(
    root: Path,
    target_name: str,
    desired: dict[Path, str],
    previous_managed: set[Path],
    mergeable_paths: set[Path],
    check: bool,
) -> int:
    conflicts, changed, stale = analyze_sync(desired, previous_managed, mergeable_paths)
    removed: list[Path] = []

    if conflicts:
        print("sync claude found unmanaged conflicts:")
        for path in conflicts:
            print(f"- {path}")
        print("resolve them manually or move the source of truth into `.flow/` first")
        return 1

    if check:
        if not changed and not stale:
            print(f"{target_name} sync check: up to date")
            return 0
        print(f"{target_name} sync check: drift detected")
        for path in changed:
            print(f"- update: {path}")
        for path in stale:
            print(f"- remove: {path}")
        return 1

    for path in stale:
        path.unlink()
        remove_empty_parents(path, root)
        removed.append(path)

    for target, content in desired.items():
        ensure_dir(target.parent)
        if not target.exists() or target.read_text() != content:
            target.write_text(content)
        if target.suffix == ".sh":
            target.chmod(0o755)

    print(f"{target_name} sync wrote managed files:")
    for path in changed:
        print(f"- {path}")
    for path in removed:
        print(f"- removed: {path}")
    if not changed and not removed:
        print("- no changes needed")
    return 0


def desired_outputs_for_target(
    target: str, root: Path, flow_dir: Path, manifest: dict, manifest_rel: str
) -> tuple[dict[Path, str], list[dict], set[Path]]:
    if target == "claude":
        return desired_claude_outputs(root, flow_dir, manifest, manifest_rel)
    if target == "codex":
        return desired_codex_outputs(root, flow_dir, manifest, manifest_rel)
    raise ValueError(f"unsupported sync target: {target}")


def setup_machine() -> int:
    ensure_dir(FLOW_HOME)
    ensure_dir(USER_BIN_DIR)
    ensure_dir(FLOW_HOME / "hooks")
    ensure_dir(FLOW_HOME / "templates")
    ensure_dir(FLOW_HOME / "user")
    ensure_dir(FLOW_HOME / "logs")
    ensure_file(
        FLOW_CONFIG,
        "[flow]\nframework_home = \"~/.flow/framework\"\nlauncher = \"~/.local/bin/flow\"\n",
    )
    print(f"flow home ready: {FLOW_HOME}")
    print(f"config:     {FLOW_CONFIG}")
    print("next: run `flow setup project` inside a repository")
    return 0


def setup_project() -> int:
    root = repo_root()
    target = root / ".flow"
    ensure_dir(target)

    for item in TEMPLATES_DIR.iterdir():
        copy_if_missing(item, target / item.name)

    print(f"project scaffold ready: {target}")
    print("next: fill in .flow/PROJECT.md and run `flow sync claude` later")
    return 0


def refresh_project() -> int:
    root = repo_root()
    target = root / ".flow"
    if not target.exists():
        print("repo is missing .flow; run `flow setup project` first")
        return 1

    added = 0
    skipped = 0
    for item in TEMPLATES_DIR.iterdir():
        item_added, item_skipped = sync_missing_tree(item, target / item.name)
        added += item_added
        skipped += item_skipped

    print(f"project refresh complete: {target}")
    print(f"added missing files: {added}")
    print(f"left existing files unchanged: {skipped}")
    return 0


def doctor() -> int:
    root = repo_root()
    flow_dir = root / ".flow"
    manifest_ok = (flow_dir / "flow.toml").exists()
    skills_dir = root / ".claude" / "skills"
    agents_dir = root / ".claude" / "agents"
    claude_managed_ok = False
    claude_drift = "n/a"
    codex_skills_dir = root / ".codex" / "skills"
    codex_managed_ok = False
    codex_drift = "n/a"

    if manifest_ok:
        try:
            manifest_path, manifest = load_flow_manifest(flow_dir)
            claude_drift, claude_managed_ok = runtime_status(root, flow_dir, manifest_path, manifest, "claude")
            codex_drift, codex_managed_ok = runtime_status(root, flow_dir, manifest_path, manifest, "codex")
        except Exception:
            claude_drift = "error"
            codex_drift = "error"

    print(f"python:      {sys.executable}")
    print(f"flow home:   {FLOW_HOME}")
    print(f"framework:   {FRAMEWORK_DIR}")
    print(f"repo:        {root}")
    print(f"config:      {'ok' if FLOW_CONFIG.exists() else 'missing'}")
    print(f"launcher:    {'ok' if (USER_BIN_DIR / 'flow').exists() else 'missing'}")
    print(f"templates:   {'ok' if TEMPLATES_DIR.exists() else 'missing'}")
    print(f"repo .flow:  {'ok' if flow_dir.exists() else 'missing'}")
    print(f"manifest:    {'ok' if manifest_ok else 'missing'}")
    print(f"claude sync: {'ok' if claude_managed_ok else 'missing'}")
    print(f"claude drift:{claude_drift}")
    print(f"skills dir:  {'ok' if skills_dir.exists() else 'missing'}")
    print(f"agents dir:  {'ok' if agents_dir.exists() else 'missing'}")
    print(f"codex sync:  {'ok' if codex_managed_ok else 'missing'}")
    print(f"codex drift: {codex_drift}")
    print(f"codex skills:{'ok' if codex_skills_dir.exists() else 'missing'}")
    return 0


def bootstrap() -> int:
    root = repo_root()
    flow_dir = root / ".flow"
    if not flow_dir.exists():
        print("repo is missing .flow; run `flow setup project` first")
        return 1

    required = [
        flow_dir / "flow.toml",
        flow_dir / "FRAMEWORK.md",
        flow_dir / "PROJECT.md",
        flow_dir / "commands",
        flow_dir / "agents",
        flow_dir / "standards",
        flow_dir / "project",
        flow_dir / "memory",
        flow_dir / "templates",
    ]
    missing = [str(p) for p in required if not p.exists()]
    if missing:
        print("bootstrap found missing framework paths:")
        for path in missing:
            print(f"- {path}")
        return 1

    print(f"bootstrap ok: {flow_dir}")
    print("next: run `flow doctor` or `flow sync claude`")
    return 0


def sync_target(target: str, check: bool = False) -> int:
    root = repo_root()
    flow_dir = root / ".flow"
    if not flow_dir.exists():
        print("repo is missing .flow; run `flow setup project` first")
        return 1

    try:
        manifest_path, manifest = load_flow_manifest(flow_dir)
    except FileNotFoundError as err:
        print(str(err))
        return 1

    runtime = manifest.get(target)
    if not isinstance(runtime, dict):
        print(f"sync target is not configured in .flow/flow.toml: {target}")
        return 1

    previous_managed = read_managed_paths(root, root / runtime["managed_manifest"])
    desired, _managed_entries, mergeable_paths = desired_outputs_for_target(
        target, root, flow_dir, manifest, rel_posix(manifest_path, root)
    )
    result = sync_outputs(root, target, desired, previous_managed, mergeable_paths, check=check)
    if result == 0:
        mode = "check" if check else "sync"
        print(f"{target} {mode} complete from {manifest_path}")
    return result


def main() -> int:
    parser = argparse.ArgumentParser(
        prog="flow",
        description="Portable AI workflow framework CLI.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=(
            "Common examples:\n"
            "  flow setup machine\n"
            "  flow setup project\n"
            "  flow bootstrap\n"
            "  flow sync claude\n"
            "  flow sync codex --check\n"
            "  flow doctor\n"
        ),
    )
    sub = parser.add_subparsers(dest="command", required=True, title="commands")

    setup = sub.add_parser(
        "setup",
        help="prepare the machine install or scaffold .flow into the current repo",
        description="Prepare machine-local flow support or scaffold the project-local .flow source of truth.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=(
            "Examples:\n"
            "  flow setup machine\n"
            "  flow setup project\n"
        ),
    )
    setup_sub = setup.add_subparsers(dest="setup_target", required=True, title="setup targets")
    setup_sub.add_parser(
        "machine",
        help="create ~/.flow support directories, config, and launcher expectations",
        description="Create the machine-local flow home, config, and support directories under ~/.flow.",
    )
    setup_sub.add_parser(
        "project",
        help="scaffold .flow into the current repository",
        description="Copy missing framework template files into repo/.flow without touching existing files.",
    )

    refresh = sub.add_parser(
        "refresh",
        help="add newly introduced framework files into an existing repo/.flow",
        description="Refresh an existing repo-local .flow by copying only files that are missing.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="Example:\n  flow refresh project\n",
    )
    refresh_sub = refresh.add_subparsers(dest="refresh_target", required=True, title="refresh targets")
    refresh_sub.add_parser(
        "project",
        help="copy missing files from the framework template into repo/.flow",
        description="Bring an existing project forward to the latest template surface without overwriting local edits.",
    )

    sub.add_parser(
        "doctor",
        help="report machine, repo, and runtime sync state",
        description="Inspect the current machine install, repo framework, and generated runtime adapter state.",
    )
    sub.add_parser(
        "bootstrap",
        help="validate that the required repo/.flow structure exists",
        description="Check that the current repository contains the minimum .flow structure needed for sync and workflow use.",
    )
    sync = sub.add_parser(
        "sync",
        help="generate runtime adapters from repo/.flow",
        description="Generate runtime-facing adapters from the repo-local .flow source of truth.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=(
            "Targets:\n"
            "  claude  Generate .claude skills, agents, hooks, settings, and a managed manifest.\n"
            "  codex   Generate .codex skills and a managed manifest.\n\n"
            "Examples:\n"
            "  flow sync claude\n"
            "  flow sync claude --check\n"
            "  flow sync codex\n"
            "  flow sync codex --check\n"
        ),
    )
    sync.add_argument(
        "target",
        choices=["claude", "codex"],
        help="runtime adapter target to generate or check",
    )
    sync.add_argument(
        "--check",
        action="store_true",
        help="report drift without writing files",
    )

    args = parser.parse_args()

    if args.command == "setup" and args.setup_target == "machine":
        return setup_machine()
    if args.command == "setup" and args.setup_target == "project":
        return setup_project()
    if args.command == "refresh" and args.refresh_target == "project":
        return refresh_project()
    if args.command == "doctor":
        return doctor()
    if args.command == "bootstrap":
        return bootstrap()
    if args.command == "sync":
        return sync_target(args.target, check=args.check)
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
