"""Machine paths, sync/install mode names, and release-roster constants.

The bottom of the `cli/` dependency graph: this module imports nothing from its
siblings, and every sibling imports from it. That direction is what keeps the
graph acyclic — the constants below were previously module-level in `flow.py`,
so any module extracted from `flow.py` that also needed them would have had to
import back into the entrypoint that imports it.

`HOME` resolves at import time, which is what makes the test suite's fake-HOME
subprocesses work: each `flow` invocation is a fresh process, so `HOME` picks up
the environment it was launched with. Making it lazy would be an improvement and
a behavior change; it is deliberately neither here.
"""

import re
from pathlib import Path

HOME = Path.home()
FLOW_HOME = HOME / ".flow"
SOURCE_DIR = FLOW_HOME / "source"
SCAFFOLD_DIR = SOURCE_DIR / "scaffolds" / "default"
USER_OVERLAY_DIR = FLOW_HOME / "user"
USER_BIN_DIR = HOME / ".local" / "bin"
FLOW_CONFIG = FLOW_HOME / "config.toml"
GENERATED_MARKER = "Generated by flow."
DEFAULT_REMOTE = "https://github.com/andyconley/flow.git"
# Release roster uses a blacklist, not a whitelist (backlog P8 fix).
#
# Why: previously the roster was a whitelist of dirs and files to include. When
# a new top-level item was added in version B and a user updated A → C
# (skipping B), the swap was done by A's code using A's whitelist — silently
# missing the new item. Observed concretely in v0.4.5 (which added
# CHANGELOG.md): users updating from v0.4.4 directly to v0.5.0 had CHANGELOG.md
# silently omitted.
#
# Blacklist semantics: copy every non-dotfile top-level entry except those
# explicitly excluded. New top-level files added in future versions are
# included automatically, no roster-update needed in older clients.
RELEASE_EXCLUDE_TOP_LEVEL = (
    "tests",            # dev-only — release-installed surfaces shouldn't carry tests
    "install-flow.sh",  # the bootstrap script lives in the clone; `flow update` is the post-install path
    "install.sh",       # same — curl-able bootstrap, not part of the runtime
)
RELEASE_EXCLUDE_DIRS = ("__pycache__", ".agents", ".claude", ".codex", ".git")  # recursive cleanup

# Which paths inside a project's `.flow/` hold framework capability, as opposed
# to the project's own state. Two constants, derived, rather than two lists:
# `bootstrap` reports on the directories only, while the audit also classifies
# FRAMEWORK.md, and two independently maintained spellings of "which paths are
# framework capability" is exactly the drift that would let a later migration
# delete something no audit ever showed.
#
# Deliberately excluded, and this is the safety property rather than an
# omission: PROJECT.md, flow.toml, memory/, and runs/ are project state. A path
# absent from here is never walked by the audit, and therefore can never be
# proposed for deletion by anything consuming the audit's output.
#
# Plain strings, not Path: everything else in this module that is a Path is
# absolute, and findings are keyed on POSIX-relative strings. Callers join.
CAPABILITY_DIRS = ("agents", "commands", "project", "standards", "templates")
CAPABILITY_PATHS = CAPABILITY_DIRS + ("FRAMEWORK.md",)

RELEASE_EXCLUDE_FILE_PATTERNS = ("*.pyc", ".DS_Store")
SEMVER_TAG_RE = re.compile(r"^v(\d+)\.(\d+)\.(\d+)(?:[-+][\w.-]+)?$")

# Codex moved standalone skill discovery from `.codex/skills` to the shared
# agent-skills locations. Normalize the legacy value so existing project
# overlays migrate on their next sync without requiring a manifest edit.
LEGACY_CODEX_SKILL_DIR = ".codex/skills"
CODEX_SKILL_DIR = ".agents/skills"

# Install modes
INSTALL_MODE_DEVELOP = "develop"
INSTALL_MODE_RELEASE = "release"
